### ISSUE TITLE
Not catching HTTPErrors properly

### ISSUE THREAD

**Issue by jacobdadams** [agrc/agol-validator#14]
Program is not catching HTTPErrors properly, possibly because try/except is in `validate.py` instead of within the individual instance methods of `checks.py`?

<details>
  <summary>traceback</summary>

```
Checking Utah USGS 3DEP 1K Grid...
Traceback (most recent call last):
  File "C:\Users\jdadams\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\validate\lib\site-packages\arcgis\_impl\connection.py", line 852, in get
    resp = opener.open(url)
  File "C:\Users\jdadams\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\validate\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\jdadams\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\validate\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\jdadams\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\validate\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\jdadams\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\validate\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\jdadams\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\validate\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 498: 498

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jdadams\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\validate\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\jdadams\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\validate\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\gis\git\agol-validator\__main__.py", line 47, in <module>
    main()
  File "c:\gis\git\agol-validator\__main__.py", line 40, in main
    org_validator.check_items(report_dir)
  File "c:\gis\git\agol-validator\validate.py", line 186, in check_items
    checker.metadata_check()
  File "c:\gis\git\agol-validator\checks.py", line 363, in metadata_check
    if self.arcpy_metadata and self.arcpy_metadata.xml != self.item.metadata:
  File "C:\Users\jdadams\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\validate\lib\site-packages\arcgis\gis\__init__.py", line 6993, in __getattribute__
    return super(Item, self).__getattribute__(name)
  File "C:\Users\jdadams\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\validate\lib\site-packages\arcgis\gis\__init__.py", line 7462, in metadata
    return self._portal.con.get(metadataurlpath, try_json=False)
  File "C:\Users\jdadams\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\validate\lib\site-packages\arcgis\_impl\connection.py", line 927, in get
    return self.get(newpath, ssl, try_json, is_retry=True)
  File "C:\Users\jdadams\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\validate\lib\site-packages\arcgis\_impl\connection.py", line 816, in get
    params['f'] = 'json'
TypeError: 'bool' object does not support item assignment
```

</details

**Comment by jacobdadams** [comment]
PEBKAC. Ignore.

(It was catching it properly- it was just re-raising the exception. The finally clause executed properly. Issue #15 is still valid.)
